### ISSUE TITLE
Dataset Release

### ISSUE THREAD

**Issue by wangwenhaoxiaotie** [ntunlp/xCodeEval#1]
Hello, When will you plan to release the dataset? thank you!

**Comment by sbmaruf** [comment]
Within a few hours. :heart:

**Comment by wangwenhaoxiaotie** [comment]
Thank you!

**Comment by aksh555** [comment]
Hi, has the dataset for Program Synthesis been released? 
Thanks!

**Comment by sbmaruf** [comment]
Hi! @aksh555  Thanks for informing us that you didn't find the "Program Synthesis" data in the repo.
Earlier we already uploaded all the data in the [huggingface repo](https://huggingface.co/datasets/NTU-NLP-sg/xCodeEval) but didn't update the proper documentation in the [xCodeEval](https://github.com/ntunlp/xCodeEval) Repo.
Now that we have updated the proper documentation here, feel free to go ahead and see if you can figure out where is the "Program Synthesis" and how to get that. Do let us know if you find any broken links, anything confusing, or if any instruction is not working. 
If you still can't find the data, here is the link of the program synthesis doc, https://github.com/ntunlp/xCodeEval/blob/main/program_synthesis.md

**Comment by sbmaruf** [comment]
Closing the issue. Please open it if you have any more query.
