### ISSUE TITLE
Releasing plan of Santacoder DPR checkpoint

### ISSUE THREAD

**Issue by sh0416** [ntunlp/xCodeEval#5]
Could I access to the checkpoint of DPR santacoder?

**Comment by sbmaruf** [comment]
Hi, @sh0416. Thanks for reaching out. I apologize for not getting back to you earlier. All of us were busy due to the EMNLP deadline. We are planning to release it as soon as possible, potentially next Monday. In the meantime, if you have any queries, please let us know.

**Comment by Jackal1586** [comment]
Please access the models from huggingface:

1. **nl-code**: [NTU-NLP-sg/xCodeEval-nl-code-starencoder-ckpt-37](https://huggingface.co/NTU-NLP-sg/xCodeEval-nl-code-starencoder-ckpt-37)
2. **code-code**: [NTU-NLP-sg/xCodeEval-code-code-starencoder-ckpt-37](https://huggingface.co/NTU-NLP-sg/xCodeEval-code-code-starencoder-ckpt-37)

**Comment by Jackal1586** [comment]
Stay tuned for more checkpoints.

**Comment by sh0416** [comment]
Thanks for your support. Great work.
